# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "novarocks-connector-iceberg"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
base64.workspace = true
iceberg = "0.9.0"
iceberg-catalog-rest = "0.9.0"
iceberg-catalog-hms = "0.9.0"
opendal = { workspace = true, features = ["services-oss", "services-fs", "services-s3", "services-hdfs-native", "services-memory"] }
arrow = { workspace = true, features = ["prettyprint", "ipc", "ipc_compression"] }
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
crc32fast = "1"
futures.workspace = true
ordered-float = "4"
parquet = { workspace = true, features = ["arrow", "variant_experimental"] }
prost.workspace = true
rand.workspace = true
roaring.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
typetag = "0.2"
url.workspace = true
uuid = { workspace = true, features = ["v4", "v7", "serde"] }
novarocks-fs.workspace = true
novarocks-connector-iceberg-functions.workspace = true
novarocks-proto-codec.workspace = true
novarocks-proto-models.workspace = true
novarocks-spi.workspace = true
novarocks-types.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
