[package]
name = "novarocks-proto-codec"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
arrow-schema.workspace = true
bytes.workspace = true
once_cell.workspace = true
prost.workspace = true
prost-reflect.workspace = true
sha2.workspace = true
novarocks-types.workspace = true
novarocks-proto-models.workspace = true
novarocks-spi.workspace = true

[dev-dependencies]
uuid = { workspace = true, features = ["v4"] }
