[package]
name = "novarocks-execution"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
arrow = { version = "58.2.0" }
bytes = "1"
datasketches = "0.2.0"
novarocks-types = { path = "../types" }
novarocks-spi = { path = "../spi" }
sha2 = "0.10"
tokio = { version = "1", features = ["rt-multi-thread"] }

[dev-dependencies]
futures = "0.3"
