# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "novarocks-functions"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[features]
test-support = []

[dependencies]
datasketches = { workspace = true, features = ["hll"] }
openssl.workspace = true
url.workspace = true
arrow-arith = "58.2.0"
arrow-ord = "58.2.0"
regex.workspace = true
roaring.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
allocator-api2.workspace = true
hashbrown = { workspace = true, features = ["raw", "allocator-api2"] }
hex.workspace = true
base64.workspace = true
arrow-array.workspace = true
arrow-buffer.workspace = true
arrow-cast.workspace = true
arrow-data.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
md-5.workspace = true
novarocks-type-contract.workspace = true
novarocks-function-contract.workspace = true
novarocks-constant-contract.workspace = true
num-traits.workspace = true
rand.workspace = true
ryu.workspace = true
sha2.workspace = true
sm3.workspace = true

twox-hash.workspace = true
