[package]
name = "novarocks-local-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
novarocks-connector-contract.workspace = true
novarocks-physical-plan.workspace = true
novarocks-local-program.workspace = true
novarocks-functions.workspace = true
novarocks-types.workspace = true
arrow-array.workspace = true
arrow-select.workspace = true
arrow-schema.workspace = true
novarocks-type-contract.workspace = true

[dev-dependencies]
bytes.workspace = true
novarocks-connector-iceberg-functions.workspace = true
