-- Migrated from: dev/test/sql/test_window_function/T/test_basic_multi_window_function
-- Test Objective:
-- 1. Validate queries using multiple window functions in the same SELECT list.
-- 2. Cover combinations: removable cumulative + non-removable, with lead/lag mixed in.
-- 3. With and without PARTITION BY.

-- query 1
-- @skip_result_check=true
CREATE TABLE ${case_db}.t0 (
  `v1` int(11) NULL,
  `v2` int(11) NULL,
  `v3` int(11) NOT NULL,
  `v4` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
 "replication_num" = "1"
);
INSERT INTO ${case_db}.t0 (v1, v2, v3, v4) values
    (1, 1, 1, NULL),
    (1, 1, 2, NULL),
    (1, NULL, 3, NULL),
    (1, NULL, 4, NULL),
    (1, 2, 5, NULL),
    (1, 2, 6, NULL),
    (1, NULL, 7, NULL),
    (1, NULL, 8, NULL),
    (2, 3, 9, NULL),
    (2, 3, 10, NULL),
    (2, NULL, 11, NULL),
    (2, NULL, 12, NULL),
    (2, 4, 13, NULL),
    (2, 4, 14, NULL),
    (2, NULL, 15, NULL),
    (2, NULL, 16, NULL),
    (NULL, 3, 17, NULL),
    (NULL, 3, 18, NULL),
    (NULL, NULL, 19, NULL),
    (NULL, NULL, 20, NULL),
    (NULL, 4, 21, NULL),
    (NULL, 4, 22, NULL),
    (NULL, NULL, 23, NULL),
    (NULL, NULL, 24, NULL);
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 (v1, v2, v3, v4) values
    (101, 101, 101, NULL),
    (101, 101, 102, NULL),
    (101, NULL, 103, NULL),
    (101, NULL, 104, NULL),
    (101, 102, 105, NULL),
    (101, 102, 106, NULL),
    (101, NULL, 107, NULL),
    (101, NULL, 108, NULL),
    (102, 103, 109, NULL),
    (102, 103, 110, NULL),
    (102, NULL, 111, NULL),
    (102, NULL, 112, NULL),
    (102, 104, 113, NULL),
    (102, 104, 114, NULL),
    (102, NULL, 115, NULL),
    (102, NULL, 116, NULL),
    (NULL, 103, 117, NULL),
    (NULL, 103, 118, NULL),
    (NULL, NULL, 119, NULL),
    (NULL, NULL, 120, NULL),
    (NULL, 104, 121, NULL),
    (NULL, 104, 122, NULL),
    (NULL, NULL, 123, NULL),
    (NULL, NULL, 124, NULL);
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
CREATE TABLE ${case_db}.t1 (
  `v1` decimal64(18,5) NULL,
  `v2` decimal64(18,5) NULL,
  `v3` decimal64(18,5) NOT NULL,
  `v4` decimal64(18,5) NULL,
  `v5` decimal64(18,5) NOT NULL,
  `v6` decimal64(18,5) NOT NULL,
  `v7` decimal64(18,5) NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
 "replication_num" = "1"
);
INSERT INTO ${case_db}.t1 (v1, v2, v3, v4, v5, v6, v7)
SELECT v1, v2, v3, v4,
row_number() OVER (ORDER BY v1, v2, v3, v4) as v5,
row_number() OVER (PARTITION BY v1 ORDER BY v2, v3, v4) as v6,
1 as v7
FROM ${case_db}.t0;

-- query 2
-- MULTI(HAS_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 3
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 4
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 5
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 6
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 7
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 8
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v2) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 9
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 10
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 11
-- MULTI(HAS_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 12
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 13
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 14
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 15
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 16
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 17
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 18
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 19
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 20
-- MULTI(NOT_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 21
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 22
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 23
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 24
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 25
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 26
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v3) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 27
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 28
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 29
-- MULTI(NOT_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 30
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 31
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 32
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 33
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 34
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 35
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 36
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 37
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 38
-- MULTI(ALL_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 39
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 40
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 41
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 42
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 43
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 44
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v4) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 45
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 46
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 47
-- MULTI(ALL_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 48
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 49
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 50
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 51
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 52
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 53
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 54
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 55
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 56
-- MULTI(HAS_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 57
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 58
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 59
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 60
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 61
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 62
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v2) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 63
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 64
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 65
-- MULTI(HAS_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 66
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 67
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 68
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 69
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 70
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 71
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 72
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 73
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v2 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 74
-- MULTI(NOT_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 75
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 76
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 77
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 78
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 79
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 80
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v3) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 81
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 82
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 83
-- MULTI(NOT_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 84
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 85
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 86
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 87
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 88
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 89
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 90
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 91
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v3 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v3 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 92
-- MULTI(ALL_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 93
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 94
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 95
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 96
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 97
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 98
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v4) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 99
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 100
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4 IGNORE NULLS) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 101
-- MULTI(ALL_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 102
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 103
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 104
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 105
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 106
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 107
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2
    FROM ${case_db}.t1
) a;

-- query 108
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 109
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2),
    SUM(wv3), AVG(wv3), MIN(wv3), MAX(wv3),
    SUM(wv4), AVG(wv4), MIN(wv4), MAX(wv4)
FROM (
    SELECT
        AVG(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv1,
        MAX(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv2,
        FIRST_VALUE(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv3,
        LAST_VALUE(v4 IGNORE NULLS) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv4
    FROM ${case_db}.t1
) a;

-- query 110
-- MULTI(HAS_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v2, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 111
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v2 IGNORE NULLS, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 112
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v2, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 113
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v2 IGNORE NULLS, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 114
-- MULTI(HAS_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v2, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 115
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v2 IGNORE NULLS, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 116
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v2, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 117
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v2 IGNORE NULLS, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 118
-- MULTI(NOT_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v3, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 119
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v3 IGNORE NULLS, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 120
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v3, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 121
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v3 IGNORE NULLS, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 122
-- MULTI(NOT_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v3, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 123
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v3 IGNORE NULLS, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 124
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v3, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 125
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v3 IGNORE NULLS, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 126
-- MULTI(ALL_NULL) without partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v4, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 127
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v4 IGNORE NULLS, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 128
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v4, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 129
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v4 IGNORE NULLS, 3) OVER(ORDER BY v5) AS wv1,
        SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 130
-- MULTI(ALL_NULL) with partition by
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v4, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 131
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LEAD(v4 IGNORE NULLS, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 FOLLOWING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 132
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v4, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

-- query 133
SELECT
    SUM(wv1), AVG(wv1), MIN(wv1), MAX(wv1),
    SUM(wv2), AVG(wv2), MIN(wv2), MAX(wv2)
FROM (
    SELECT
        LAG(v4 IGNORE NULLS, 3) OVER(PARTITION BY v1 ORDER BY v5) AS wv1,
        SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 3 PRECEDING) AS wv2
    FROM ${case_db}.t1
) a;

