-- Migrated from: dev/test/sql/test_window_function/T/test_basic_window_function
-- Test Objective:
-- 1. Validate COUNT and SUM window functions across all ROWS/RANGE frame types
-- 2. Test with NULL-containing, non-null, and all-null columns
-- 3. Test with and without PARTITION BY

-- query 1
-- @skip_result_check=true
CREATE TABLE ${case_db}.t0 (
    `v1` int(11) NULL,
    `v2` int(11) NULL,
    `v3` int(11) NOT NULL,
    `v4` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
    "replication_num" = "1"
);

INSERT INTO ${case_db}.t0 (v1, v2, v3, v4) values
    (1, 1, 1, NULL),
    (1, 1, 2, NULL),
    (1, NULL, 3, NULL),
    (1, NULL, 4, NULL),
    (1, 2, 5, NULL),
    (1, 2, 6, NULL),
    (1, NULL, 7, NULL),
    (1, NULL, 8, NULL),
    (2, 3, 9, NULL),
    (2, 3, 10, NULL),
    (2, NULL, 11, NULL),
    (2, NULL, 12, NULL),
    (2, 4, 13, NULL),
    (2, 4, 14, NULL),
    (2, NULL, 15, NULL),
    (2, NULL, 16, NULL),
    (NULL, 3, 17, NULL),
    (NULL, 3, 18, NULL),
    (NULL, NULL, 19, NULL),
    (NULL, NULL, 20, NULL),
    (NULL, 4, 21, NULL),
    (NULL, 4, 22, NULL),
    (NULL, NULL, 23, NULL),
    (NULL, NULL, 24, NULL);

INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
INSERT INTO ${case_db}.t0 SELECT * FROM ${case_db}.t0;
-- This point for v1, values `1`, `2`, `NULL` all have 32768 rows

INSERT INTO ${case_db}.t0 (v1, v2, v3, v4) values
    (1, 1111, 1111, NULL),
    (1, 1111, 2222, NULL),
    (1, NULL, 3333, NULL),
    (1, NULL, 4444, NULL),
    (1, 2222, 5555, NULL),
    (1, 2222, 6666, NULL),
    (1, NULL, 7777, NULL),
    (1, NULL, 8888, NULL),
    (101, 101, 101, NULL),
    (101, 101, 102, NULL),
    (101, NULL, 103, NULL),
    (101, NULL, 104, NULL),
    (101, 102, 105, NULL),
    (101, 102, 106, NULL),
    (101, NULL, 107, NULL),
    (101, NULL, 108, NULL),
    (102, 103, 109, NULL),
    (102, 103, 110, NULL),
    (102, NULL, 111, NULL),
    (102, NULL, 112, NULL),
    (102, 104, 113, NULL),
    (102, 104, 114, NULL),
    (102, NULL, 115, NULL),
    (102, NULL, 116, NULL),
    (NULL, 103, 117, NULL),
    (NULL, 103, 118, NULL),
    (NULL, NULL, 119, NULL),
    (NULL, NULL, 120, NULL),
    (NULL, 104, 121, NULL),
    (NULL, 104, 122, NULL),
    (NULL, NULL, 123, NULL),
    (NULL, NULL, 124, NULL);
-- This point for v1, value `1` and `NULL` are not an integer multiple of chunk_size

CREATE TABLE ${case_db}.t1 (
    `v1` decimal64(18,5) NULL,
    `v2` decimal64(18,5) NULL,
    `v3` decimal64(18,5) NOT NULL,
    `v4` decimal64(18,5) NULL,
    `v5` decimal64(18,5) NOT NULL,
    `v6` decimal64(18,5) NOT NULL,
    `v7` decimal64(18,5) NOT NULL,
    `v8` decimal64(18,5) NOT NULL,
    `v9` decimal64(18,5) NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
    "replication_num" = "1"
);

INSERT INTO ${case_db}.t1 (v1, v2, v3, v4, v5, v6, v7, v8, v9)
SELECT v1, v2, v3, v4, v5, v6,
mod(v5, 128) as v7,
mod(v6, 32) as v8,
1 as v9
FROM (
    SELECT v1, v2, v3, v4,
    row_number() OVER (ORDER BY v1, v2, v3, v4) as v5,
    row_number() OVER (PARTITION BY v1 ORDER BY v2, v3, v4) as v6
    FROM ${case_db}.t0
) tmp;

-- query 2
-- COUNT(HAS_NULL) without partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 3
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 4
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 5
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 6
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 7
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 8
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 9
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 10
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 11
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 12
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 13
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 14
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 15
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 16
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 17
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 18
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 19
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 20
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 21
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 22
-- COUNT(HAS_NULL) with partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 23
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 24
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 25
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 26
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 27
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 28
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 29
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 30
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 31
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 32
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 33
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 34
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 35
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 36
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 37
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 38
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 39
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 40
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 41
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v2) OVER(PARTITION BY v1 ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 42
-- COUNT(NOT_NULL) without partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 43
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 44
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 45
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 46
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 47
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 48
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 49
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 50
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 51
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 52
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 53
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 54
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 55
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 56
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 57
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 58
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 59
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 60
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 61
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 62
-- COUNT(NOT_NULL) with partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 63
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 64
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 65
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 66
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 67
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 68
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 69
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 70
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 71
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 72
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 73
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 74
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 75
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 76
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 77
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 78
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 79
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 80
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 81
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v3) OVER(PARTITION BY v1 ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 82
-- COUNT(ALL_NULL) without partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 83
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 84
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 85
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 86
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 87
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 88
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 89
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 90
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 91
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 92
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 93
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 94
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 95
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 96
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 97
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 98
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 99
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 100
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 101
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 102
-- COUNT(ALL_NULL) with partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 103
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 104
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 105
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 106
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 107
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 108
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 109
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 110
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 111
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 112
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 113
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 114
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 115
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 116
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 117
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 118
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 119
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 120
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 121
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT COUNT(v4) OVER(PARTITION BY v1 ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 122
-- SUM(HAS_NULL) without partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 123
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 124
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 125
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 126
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 127
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 128
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 129
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 130
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 131
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 132
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 133
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 134
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 135
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 136
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 137
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 138
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 139
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 140
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 141
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 142
-- SUM(HAS_NULL) with partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 143
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 144
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 145
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 146
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 147
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 148
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 149
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 150
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 151
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 152
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 153
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 154
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 155
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 156
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 157
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 158
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 159
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 160
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 161
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v2) OVER(PARTITION BY v1 ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 162
-- SUM(NOT_NULL) without partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 163
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 164
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 165
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 166
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 167
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 168
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 169
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 170
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 171
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 172
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 173
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 174
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 175
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 176
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 177
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 178
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 179
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 180
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 181
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 182
-- SUM(NOT_NULL) with partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 183
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 184
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 185
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 186
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 187
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 188
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 189
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 190
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 191
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 192
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 193
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 194
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 195
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 196
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 197
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 198
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 199
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 200
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 201
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v3) OVER(PARTITION BY v1 ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 202
-- SUM(ALL_NULL) without partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 203
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 204
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 205
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 206
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 207
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 208
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 209
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 210
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 211
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 212
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 213
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 214
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 215
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 216
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 217
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 218
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 219
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 220
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 221
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 222
-- SUM(ALL_NULL) with partition by
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 223
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 224
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 225
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 226
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10 PRECEDING AND 5 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 227
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 228
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 FOLLOWING AND 10 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 229
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 230
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 231
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 15000 PRECEDING AND 5000 PRECEDING) AS wv FROM ${case_db}.t1) a;

-- query 232
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 PRECEDING AND 5000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 233
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 5000 FOLLOWING AND 15000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 234
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN 10000 PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 235
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 ROWS BETWEEN CURRENT ROW AND 10000 FOLLOWING) AS wv FROM ${case_db}.t1) a;

-- query 236
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v4 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 237
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v5 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 238
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v6 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 239
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v7 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 240
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v8 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;

-- query 241
SELECT SUM(wv), AVG(wv), MIN(wv), MAX(wv) FROM (SELECT SUM(v4) OVER(PARTITION BY v1 ORDER BY v9 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS wv FROM ${case_db}.t1) a;
